version: '3.8'

services:
  # 2. Node.js Application
  app:
    build: .
    container_name: pos_app
    ports:
      - "5000:5000"
    env_file:
      - .env # Load các biến môi trường khác (JWT, SMTP, VNPAY...) từ file .env
    restart: unless-stopped

volumes:
  pgdata: